name: Reset to last tag
on: 
  push:
    branches:
      - main
jobs:
  reset-to-last-tag:
    name: "Reset to last tag"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get tags
        id: get_tags
        run: git fetch --prune --unshallow
      - name: reset tag
        id: reset_tag
        run: VERSION_PREFIX= ${{ git describe --abbrev=0 --tags }}
      - name: reset branch
        run: git reset --hard VERSION_PREFIX
      - name: push main
        id: push_main
        run: git push -f origin main