name: Reset to last tag
on: 
  push:
    branches:
      - main
jobs:
  reset-to-last-tag:
    name: "Reset to last tag"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get tags
        id: get_tags
        run: git fetch --tags 
      - name: reset tag
        id: reset_tag
        run: git reset --hard | git describe --abbrev=0 --tags